iac

diff --git a/jenkins-groovy/Jenkinsfile b/jenkins-groovy/Jenkinsfile
--- a/jenkins-groovy/Jenkinsfile
+++ b/jenkins-groovy/Jenkinsfile
@@ -1,12 +1,12 @@
 pipeline{
       environment {
-        PROJECT_ID = '<YOUR_PROJECT_ID>'
-        CLUSTER_NAME = '<YOUR_CLUSTER_NAME>'
+        PROJECT_ID = 'lab-gcp-301223'
+        CLUSTER_NAME = 'cluster-lab'
         LOCATION = '<YOUR_CLUSTER_LOCATION>'
         CREDENTIALS_ID = '<YOUR_CREDENTIAS_ID>'
     }
-    gv = load "helper.groovy"
-    
+    //gv = load "helper.groovy"
+
     agent any
        stages {
         stage('Building backend') {
@@ -14,8 +14,8 @@ pipeline{
                 docker { image 'maven:3-alpine' }
             }
             steps {
-                sh 'mvn --version' 
-                mavenBuild()
+                sh 'mvn --version'
+                    mavenBuild()
             }
         }
         stage('Building Front-end') {
@@ -28,39 +28,140 @@ pipeline{
 
             }
         }
-          stage('Building docker images') {
-            steps {
-                sh 'node --version'
-                sh 'npm build --prod'
+        
+    }
 
+
+    // post{
+    //     always{
+    //         echo "========always========"
+    //     }
+    //     success{
+    //         echo "========pipeline executed successfully ========"
+    //     }
+    //     failure{
+    //         echo "========pipeline execution failed========"
+    //     }
+    // }
+
+    // stage('Deploy to GKE') {
+    //     steps{
+    //         step([
+    //         $class: 'KubernetesEngineBuilder',
+    //         projectId: env.PROJECT_ID,
+    //         clusterName: env.CLUSTER_NAME,
+    //         location: env.LOCATION,
+    //         manifestPattern: 'manifest.yaml',
+    //         credentialsId: env.CREDENTIALS_ID,
+    //         verifyDeployments: true])
+    //     }
+    // }
+
+}
+
+def mavenBuild() {
+    sh 'mvn clean package'
+}
+
+def buildFrontEnd() {
+    sh 'npm build --prod'
+}
+
+def tagDockerImage(String dockerRegistry, String imageName,String commitId, String version) {
+    return "${dockerRegistry}/${imageName}:${commitId}-${version}"
+}
+
+def buildAndPushDockerImage(String tag) {
+    sh 'docker build -t '${tag}' .'
+    sh 'docker login -u  -p  '
+    sh 'docker push '${tag}
+}
+// ----****************************************************----------
+
+
+// --------------------------------------------------------------------------------------------------------------------------
+
+
+def getShortCommitId() {
+    return sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
+}
+
+def getGitCurrentVersionTag() {
+    def tag = sh(script: 'git describe --tags --exact-match || echo "noTag"', returnStdout: true).trim()
+    if (tag ==~ /v[\d\.]+/) {
+        return tag
+    }
+    return null
+}
+
+/**
+ * Return the version that should be used to tag the application.
+ * It is based on the version in the pom.xml, the current branch and its tag, so:
+ *   - for release or hotfix branch with a git tag like 'v.x.x.x' => return the pom version
+ *   - for release or hotfix branch without a git tag like 'v.x.x.x' => return <pom version>-rc.<build number>
+ *   - otherwise => return <pom version>-<commitId>
+ */
+def defineAppVersion(pomVersion, commitId, branchName, gitVersionTag) {
+    def appVersion = "${pomVersion}-${commitId}"
+    if (branchName.startsWith('release/') || branchName.startsWith('hotfix/')) {
+        if(gitVersionTag != null && !gitVersionTag.isEmpty()) {
+            appVersion = pomVersion
+        } else {
+            appVersion = "${pomVersion}-rc.${env.BUILD_NUMBER}"
+        }
+    }
+    return appVersion
+}
+
+def sonarAnalysis(pom, branchName) {
+    withMaven(mavenSettingsConfig: 'AF_MavenSettings') {
+        withSonarQubeEnv('Sonar Agile Fabric') {
+            def mvnSonarArgs = ''
+            if (branchName == 'develop'){
+                mvnSonarArgs = " -Dsonar.projectVersion=\'${pom.version}\'"
+            } else {
+                def sonarProps = readProperties(file: './sonar-project.properties')
+                mvnSonarArgs = "-Dsonar.projectVersion=\'${branchName}-${pom.version}\'" +
+                        " -Dsonar.projectKey=\'${sonarProps['sonar.projectKey']}-SNAPSHOT\'" +
+                        " -Dsonar.projectName=\'${sonarProps['sonar.projectName']} - SNAPSHOT\'"
             }
+            sh "./mvnw initialize sonar:sonar ${mvnSonarArgs}"
         }
     }
+}
 
-
-    post{
-        always{
-            echo "========always========"
-        }
-        success{
-            echo "========pipeline executed successfully ========"
-        }
-        failure{
-            echo "========pipeline execution failed========"
+def packageChart(nexusRepos, dockerRegistry, appVersion) {
+    docker.withRegistry("https://${dockerRegistry}", 'portus-credentials') {
+        docker.image('docker-registry.agilefabric.fr.carrefour.com/ingelog/tools/helm-kubectl:v3.2.0').inside() {
+            sh "mkdir -p ${WORKSPACE}/packages-charts"
+            sh "sed -i -e 's/version:.*/version: ${appVersion}/' chart/supplatine-app-admin/Chart.yaml"
+            sh "sed -i -e 's/appVersion:.*/appVersion: ${appVersion}/' chart/supplatine-app-admin/Chart.yaml"
+            sh "helm package chart/supplatine-app-admin/ --destination ${WORKSPACE}/packages-charts"
+            sh "helm repo index packages-charts --url ${nexusRepos}  --merge ${WORKSPACE}/packages-charts/index.yaml"
+            withCredentials([usernamePassword(credentialsId: 'nexus-cred-helm', passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')])
+                    {
+                        sh "curl -k -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} --upload-file ${WORKSPACE}/packages-charts/supplatine-app-admin-${appVersion}.tgz  ${nexusRepos}/supplatine-app-admin-${appVersion}.tgz"
+                    }
         }
     }
+}
 
-    stage('Deploy to GKE') {
-        steps{
-            step([
-            $class: 'KubernetesEngineBuilder',
-            projectId: env.PROJECT_ID,
-            clusterName: env.CLUSTER_NAME,
-            location: env.LOCATION,
-            manifestPattern: 'manifest.yaml',
-            credentialsId: env.CREDENTIALS_ID,
-            verifyDeployments: true])
-        }
+def buildImage(dockerConfig, commitId) {
+    sh "cp -R src/main/docker/* target/"
+    return docker.build("${dockerConfig.registry}/${dockerConfig.imageName}:${commitId}", 'target/')
+}
+
+def pushImageAndTag(image, dockerRegistry, tag) {
+    docker.withRegistry("https://${dockerRegistry}", 'portus-credentials') {
+        image.push()
+        image.push(tag)
     }
- 
+}
+
+def launchDeployment(deployJob, appVersion, env) {
+    build job: deployJob, quietPeriod: 1, wait: false, parameters: [
+            [$class: 'StringParameterValue', name: 'APP_NAME', value: 'supplatine-app-admin'],
+            [$class: 'StringParameterValue', name: 'APP_VERSION', value: appVersion],
+            [$class: 'StringParameterValue', name: 'APP_ENV', value: env]
+    ]
 }
